name: main

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    uses: "./.github/workflows/onchange.yml"
    secrets: inherit
  main:
    name: main
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
      - name: checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 22.1.0
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm build
          pnpm semantic-release
